# Generated by Django 2.1 on 2019-03-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWordSpider',
            fields=[
                ('id', models.AutoField(db_column='UID', max_length=11, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=32)),
                ('userId', models.IntegerField()),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(default=0, max_length=4)),
            ],
            options={
                'db_table': 'keyword_spider',
            },
        ),
    ]
